apiVersion: v1
kind: Pod
metadata:
  name: kube-auth-proxy
  namespace: default
  labels:
    app: kube-auth-proxy
spec:
  serviceAccountName: kube-auth-proxy
  containers:
    - name: kube-auth-proxy
      image: crmirror.lcpu.dev/xtlsoft/hpc_base:ubuntu2404
      ports:
        - containerPort: 8080
      resources:
        requests:
          cpu: "100m"
          memory: "128Mi"
        limits:
          cpu: "2"
          memory: "2Gi"
      command:
        - sleep
        - inf
