apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kube-auth-proxy-impersonator
  namespace: default
rules:
  - apiGroups: [""]
    resources: ["users", "groups", "serviceaccounts"]
    verbs: ["impersonate"]
  - apiGroups: ["authentication.k8s.io"]
    resources:
      [
        "uids",
        "userextras/name",
        "userextras/realname",
        "userextras/email",
        "userextras/telephone",
        "userextras/school",
        "userextras/studentgrade",
      ]
    verbs: ["impersonate"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kube-auth-proxy-impersonator-binding
  namespace: default
subjects:
  - kind: ServiceAccount
    name: kube-auth-proxy
    namespace: default
roleRef:
  kind: ClusterRole
  name: kube-auth-proxy-impersonator
  apiGroup: rbac.authorization.k8s.io
